# NUMPY - Python Packages for Data Science
Numerical Python, core package to deal with multidimensional data

In [105]:
#### Importing libraries 
import numpy as np


In [42]:
# Numpy array
a= np.array([0, 1, 2, 3])

In [43]:
# Type 
a = np.array([0, 1, 2, 3])
type(a)

numpy.ndarray

In [44]:
# Shape of array 
a.shape

(4,)

In [46]:
# Acessing index element
a[0]

0

In [47]:
# Acessing index element
a[3]

3

In [49]:
# Acessing inexistent index element
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [50]:
# Right-most element
a[-1]

3

In [51]:
# Left-most (begin by -1)
a[-4]

0

In [52]:
# Acessing inexistent index element
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [53]:
# Empty array
a[:0]

array([], dtype=int64)

In [54]:
# Complete array
a[0:]

array([0, 1, 2, 3])

In [55]:
# Exclude index 0
a[1:]

array([1, 2, 3])

In [56]:
# Only element 0
a[:1]

array([0])

In [57]:
# Only the last element
a[[-1]]

array([3])

In [58]:
# Eliminate the last element
a[:-1]

array([0, 1, 2])

In [59]:
# Step
a[::2]

array([0, 2])

In [60]:
# First index to the end, step 2
a[1::2]

array([1, 3])

## Array types

In [64]:
a = np.array([0, 1, 2, 3])
b = np.array([0.0, 0.1, 0.2, 0.3])

In [65]:
type(a)

numpy.ndarray

In [66]:
a.dtype

dtype('int64')

In [67]:
type(b)

numpy.ndarray

In [68]:
b.dtype

dtype('float64')

In [74]:
# Assigning a type inside the array to float
c = np.array([0, 0.1, 2, 0.3], dtype = float)
c

array([0. , 0.1, 2. , 0.3])

In [70]:
c.dtype

dtype('float64')

In [75]:
# Assigning a type inside the array to int
# dangerous! 
d = np.array([0.0, 1, 1.2, 3.8], dtype = int)
d

array([0, 1, 1, 3])

In [72]:
d.dtype

dtype('int64')

## Dimensions and shapes 

In [76]:
# One dimension
a = np.array([0, 1 , 2, 3])

In [77]:
a.shape

(4,)

In [100]:
# Multidimensional
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]])

In [101]:
A.shape

(3, 4)

In [102]:
# Number of dimensions of A
A.ndim

2

In [91]:
# 2 matrices X 3 rows x 2 columns
B = np.array([[
        [0, 1],
        [3, 4],
        [6, 7]],
    
        [[0, 1],
        [3, 4],
        [6, 7]]])


In [92]:
B.shape

(2, 3, 2)

In [99]:
# number of dimensions of B
B.ndim

3

In [104]:
# Number of elements of B
B.size

12

In [95]:
# 3 matrices, 3 rows, 3 columns
C = np.array([
    [
        [0, 1,2],
        [3, 4, 5],
        [6, 7, 8]
    ],
    [
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 10]
    ],
     [
        [17, 13, 21],
        [15, 99, 55],
        [18, 0, 10]
    ]
])

In [96]:
C.shape

(3, 3, 3)

In [98]:
# Number of dimensions of C
C.ndim

3

In [103]:
#Number of elements of C
C.size

27

## Working with Matrices

In [2]:
# Indexing slices of matrices
A = np.array([
    [0, 1 , 2, 3],
    [4, 5, 6, 7]])

In [3]:
# Shape of matrix
A.shape

(2, 4)

In [4]:
# Row 0
A[0]

array([0, 1, 2, 3])

In [5]:
# Row 1
A[1]

array([4, 5, 6, 7])

In [6]:
# Empty array
A[:0]

array([], shape=(0, 4), dtype=int64)

In [7]:
# All from the First row 
A[:1]

array([[0, 1, 2, 3]])

In [8]:
# indentify the zeroes in every row
A[:,0]

array([0, 4])

In [16]:
# Row 0 Column 0
A[0,0]

0

In [12]:
# Row 1 Column 3
A[1,3]

7

In [15]:
#Slice: Every row but only first and second columns
A[:,1:3]

array([[1, 2],
       [5, 6]])

In [17]:
# Modification: replace whole row 0
A[0] = np.array([8, 9, 10, 11])
A

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [19]:
# Replace one row with only one value
A[1] = 98
A

array([[ 8,  9, 10, 11],
       [98, 98, 98, 98]])

## Statistics

#### Statistics with one dimension array

In [20]:
a = np.array([0, 1 , 2 , 3, 4])

In [21]:
# Sum all elements in the array
a.sum()

10

In [22]:
# Mean of the array
a.mean()

2.0

In [23]:
# Standart variation 
a.std()

1.4142135623730951

In [24]:
# Variation
a.var()

2.0

In [25]:
# Max
a.max()

4

In [26]:
# Min
a.min()

0

#### Statistics with Multidimensional Arrays

In [29]:
B = np.array ([
             [0, 1, 2, 3],
             [4, 5, 6, 7],
             [8, 9, 10, 11]])

In [30]:
B.sum()

66

In [31]:
B.mean()

5.5

In [32]:
B.std()

3.452052529534663

In [33]:
B.var()

11.916666666666666

In [34]:
B.max()

11

In [35]:
B.min()

0

In [36]:
# Sum the columns (axis 0)
B.sum(axis=0)

array([12, 15, 18, 21])

In [37]:
# Sum the lines (axis 1)
B.sum(axis=1)

array([ 6, 22, 38])

In [38]:
# Mean of the columns (axis 0)
A.mean(axis=0)

array([53. , 53.5, 54. , 54.5])

In [39]:
# Mean of the lines (axis 1)
A.mean(axis=1)

array([ 9.5, 98. ])

## Linear Algebra 

In [106]:
A = np.array([
    [0, 1, 2],
    [3, 4, 5]])

B = np.array([
    [6, 7, 8],
    [9, 10, 11]])

In [107]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [109]:
B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [110]:
# First element added to first element and so on (pairwise)
A + B

array([[ 6,  8, 10],
       [12, 14, 16]])

In [111]:
# First element minus to first element and so on (pairwise)
A - B

array([[-6, -6, -6],
       [-6, -6, -6]])

In [112]:
# Not the product, just the pairwise
A * B

array([[ 0,  7, 16],
       [27, 40, 55]])

In [113]:
# Transpose  of B
B.T

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [118]:
# A transpose to B production
A @ (B.T)

array([[ 23,  32],
       [ 86, 122]])

In [116]:
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [119]:
(A.T) @ B

array([[27, 30, 33],
       [42, 47, 52],
       [57, 64, 71]])

**Reminder:** Matrix Multiplication A<sub>mn</sub> x B<sub>np</sub>  = C<sub>mp</sub> 

# Useful functions

In [121]:
# Creates a Range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
# Creates a Range with lower and upper bounds
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [123]:
# Creates a Range with lower and upper bounds and STEP
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [125]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [126]:
# Creates a new arrangement for the elements in 5 rows and 2 columns
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [127]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
# (10) random elements in a one dimensional array - From 0 to 10
np.random.randint(0, 10, (10))

array([9, 4, 6, 7, 1, 6, 4, 4, 9, 0])

In [131]:
# (5 * 2 = 10) random elements in a multidimensional array - From 0 to 10, 5 rows, 2 columns
np.random.randint(0,10,(5,2))

array([[7, 0],
       [8, 5],
       [0, 9],
       [4, 1],
       [0, 8]])

In [133]:
#For random floats use rand
np.random.rand(2,4)

array([[0.00467918, 0.58963539, 0.17182176, 0.32438655],
       [0.23386745, 0.45046653, 0.94498954, 0.51881182]])

In [136]:
# Random with normal distribution (center, std (shape))
np.random.normal(0, 0.1, (10))

array([ 0.07118687,  0.09239519, -0.27434743,  0.05389689,  0.07811081,
       -0.01817306, -0.00597366,  0.07361681, -0.11178819, -0.01540059])

In [137]:
# # Random with normal distribution (center, std (shape))
np.random.normal(0,0.1, (2,5))

array([[ 0.03044842, -0.0747525 , -0.11478088, -0.09193022, -0.08822379],
       [-0.24219036, -0.28569026,  0.10836307, -0.12550953, -0.02610988]])

In [138]:
# Uniform distribution (shape)
np.random.uniform(0, 1, (3, 4))

array([[0.99250991, 0.52847786, 0.47716601, 0.22469572],
       [0.54012263, 0.93576771, 0.32928231, 0.83638823],
       [0.22916865, 0.01988493, 0.43941418, 0.60559206]])

In [141]:
# Sorting the random uniform distribution
a = np.random.uniform(0, 1, (2, 5))
np.sort(a)

array([[0.24492367, 0.379793  , 0.43216718, 0.58469802, 0.95394675],
       [0.00565289, 0.49064552, 0.52968636, 0.70904953, 0.96952875]])

In [142]:
# Fill matrices with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [143]:
# Fill matrices with 1s
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [146]:
# Fill +  type
np.ones((3,8), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

### See you soon! 